name: nice_parking
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
ersion: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"


dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  sqflite: ^2.0.2+1
  path_provider: ^2.0.10
  mobx: ^2.0.7
  flutter_mobx: ^2.0.6+1
  intl: ^0.17.0
  flutter_svg: ^1.0.1
  modal_bottom_sheet: ^2.0.1
  google_fonts: ^3.0.1
  jiffy: ^5.0.0
  datetime_picker_formfield: ^2.0.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.1.11
  mobx_codegen: ^2.0.7
  sqflite_common_ffi: ^2.1.1


  flutter_lints: ^1.0.0


flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/svg/
    - assets/png/
